#!/bin/sh
echo 'into'

gfsver=v16.3
mdlymdh=2023082412

mdlymd=`echo $mdlymdh | cut -c1-8`
mdlcyc=`echo $mdlymdh | cut -c9-10`
stations="744550 726320 722150"
stations="723570 723400 724560 726590"
stations="725620 722080 726450 722300 722150 722350"
stations="724560 744550 725580 724400"
stations="725580 724560 744550 745600 726490"
stations="725620 724510 727470 726450 726320"
stations="724510 722650 723630"
stations="723570 723630 722490 724560 724510 725580 726590 726620 727640" 
stations="723570 723630 722490"

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/gempak.sound
rm /lfs/h2/emc/stmp/geoffrey.manikin/gempak.sound/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/gempak.sound
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

cp /lfs/h1/ops/prod/com/gfs/${gfsver}/gfs.${mdlymd}/${mdlcyc}/atmos/gempak/gfs_${mdlymdh}.snd fmdl
#cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/gfsheat/gfs_${mdlymdh}.snd fmdl
echo $fmdl

times="120"
for time in $times; do
for stnm in $stations; do

dattim="`/lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/advtime ${mdlymdh} $time -1 x`"
validtime=`echo $dattim | cut -c1-11`
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c10-11`
fobs=/lfs/h1/ops/prod/dcom/ldmdata/gempak/uair/$ymd.snd
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/obs/uair/$ymd.snd fobs

stn=`echo $stnm | cut -c1-5`
if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = fmdl
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = capv;cinv;lclp
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  OPS GFS DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|gfs${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -15/50/5/;1
 FILTER   = 0.7
 CLEAR    = y
 PANEL    = 0
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = fobs
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6 
 AREA     = @${stn}
r

ex
EOF

done
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test2/.
exit
